# Generated by Django 3.1.3 on 2021-08-15 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectsApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='single_page',
        ),
    ]
