# Generated by Django 3.1.3 on 2020-12-06 07:28

import commonApp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('identifier', models.SlugField(max_length=100, verbose_name='identificador')),
                ('alt', models.CharField(blank=True, max_length=250, verbose_name='descrição')),
                ('attribution', models.CharField(blank=True, max_length=250, verbose_name='atribuição')),
                ('notes', models.CharField(blank=True, max_length=250, verbose_name='notas')),
                ('image_original', models.ImageField(upload_to=commonApp.models.getUploadFolder('{}-original', method='identifier'), verbose_name='imagem')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'imagem de usuário',
                'verbose_name_plural': 'imagens de usuário',
            },
        ),
        migrations.AddConstraint(
            model_name='userimage',
            constraint=models.UniqueConstraint(fields=('identifier', 'content_type', 'object_id'), name='uniqueForObject'),
        ),
    ]
