# 
# VAZ Projects
# 
# 
# Author: Marcelo Tellier Sartori Vaz <marcelotsvaz@gmail.com>



apiVersion: 1



datasources:
  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090
    isDefault: true
    
    
  - name: Loki
    type: loki
    url: http://loki:3100
    
    
  - name: CloudWatch
    type: cloudwatch
    jsonData:
        defaultRegion: ${AWS_DEFAULT_REGION}
        assumeRoleArn: ${grafanaRoleArn}