# 
# VAZ Projects
# 
# 
# Author: Marcelo Tellier Sartori Vaz <marcelotsvaz@gmail.com>



services:
    application:
        image: ${applicationImage}
        build:
            context: .
            cache_from:
              - type=local,src=../deployment/cache/buildkit/
            cache_to:
              - type=local,mode=max,compression=zstd,dest=../deployment/cache/buildkit/
            x-bake:
                output: type=image,push=true