# 
# VAZ Projects
# 
# 
# Author: Marcelo Tellier Sartori Vaz <marcelotsvaz@gmail.com>



services:
    application:
        image: ${applicationImage}
        build:
            context: .
            x-bake:
                output: type=image,compression=zstd,push=true
                cache-from:
                  - type=local,src=../deployment/buildkitCache/
                cache-to:
                  - type=local,mode=max,compression=zstd,dest=../deployment/buildkitCache/