# 
# VAZ Projects
# 
# 
# Author: Marcelo Tellier Sartori Vaz <marcelotsvaz@gmail.com>



services:
    application:
        image: ${applicationImage-}
        
        depends_on:
            memcached:
                condition: service_started
            elasticsearch:
                condition: service_healthy
        
        restart: unless-stopped
        
        environment:
          - DJANGO_SETTINGS_MODULE
          - djangoSecretKey
          - domain
          - staticFilesDomain
          - s3Endpoint
          - bucket
          - POSTGRES_PASSWORD
          - ELASTIC_PASSWORD
        
        command:
          - |-
            manage.py migrate --no-input
            manage.py search_index --populate
            uwsgi --ini config/uwsgi.ini
        
        ports: [ 3031:3031 ]
    
    
    memcached:
        image: memcached:1.6-alpine3.16
        
        restart: unless-stopped
    
    
    elasticsearch:
        image: elasticsearch:8.3.2
        
        restart: unless-stopped
        
        environment:
            discovery.type: single-node
            xpack.security.enabled: 'true'
            ELASTIC_PASSWORD:
        
        configs:
          - source: elasticsearch
            target: /usr/share/elasticsearch/config/jvm.options.d/jvm.options
        
        healthcheck:
            test: curl --silent elasticsearch:9200/_cluster/health/
            interval: 5s
            start_period: 90s



configs:
    elasticsearch:
        file: ./config/jvm.options