# 
# VAZ Projects
# 
# 
# Author: Marcelo Tellier Sartori Vaz <marcelotsvaz@gmail.com>



services:
    application:
        image: ${applicationImage-}
        
        depends_on:
            memcached:
                condition: service_started
            elasticsearch:
                condition: service_healthy
        
        environment:
          - DJANGO_SETTINGS_MODULE
          - djangoSecretKey
          - domainName
          - bucket
          - POSTGRES_PASSWORD
          - ELASTIC_PASSWORD
        
        command:
          - sh
          - -c
          - |-
            ./manage.py migrate --no-input
            ./manage.py search_index --populate
            uwsgi --ini config/uwsgi.ini
        
        ports: [ 3031:3031 ]
    
    
    memcached:
        image: memcached:1.6-bullseye
    
    
    elasticsearch:
        image: elasticsearch:7.17.0
        
        environment:
            ES_JAVA_OPTS: -Xms128m -Xmx128m
            discovery.type: single-node
            xpack.security.enabled: 'true'
            ELASTIC_PASSWORD:
        
        healthcheck:
            test: curl --silent elasticsearch:9200/_cluster/health/
            interval: 1s
            start_period: 60s
    
    
    node-exporter:
        image: prom/node-exporter:v1.3.1
        
        volumes: [ '/:/mnt/host:ro,rslave' ]
        
        pid: host
        network_mode: host
        
        command: [ --path.rootfs=/mnt/host ]
    
    
    promtail:
        image: grafana/promtail:2.4.2
        
        environment:
          - hostname
        
        volumes:
          - ./config/promtail.yaml:/etc/promtail/config.yml:ro
          - /var/log/journal:/mnt/logs/journal
        
        command: [ -config.file=/etc/promtail/config.yml, -config.expand-env=true ]