#
# VAZ Projects
#
#
# Author: Marcelo Tellier Sartori Vaz <marcelotsvaz@gmail.com>



server:
    http_listen_port: 9080
    grpc_listen_port: 0


positions:
    filename: /tmp/positions.yaml


clients:
  - url: http://monitoring:3100/loki/api/v1/push


scrape_configs:
  - job_name: syslog
    syslog:
        listen_address: 0.0.0.0:1514
        labels:
            job: nginxTest
    
  - job_name: journal
    journal:
        path: /mnt/journal
        labels:
            job: journalTest