#
# VAZ Projects
#
#
# Author: Marcelo Tellier Sartori Vaz <marcelotsvaz@gmail.com>



FROM docker:20.10.12-alpine3.15

WORKDIR /usr/local/lib/docker/cli-plugins

ADD https://github.com/docker/compose/releases/download/v2.2.3/docker-compose-linux-x86_64 docker-compose
RUN chmod +x docker-compose