#
# VAZ Projects
#
#
# Author: Marcelo Tellier Sartori Vaz <marcelotsvaz@gmail.com>



stages:
    - test
    - deploy


variables:
    PIP_CACHE_DIR: ${CI_PROJECT_DIR}/.cache/pip


default:
    image: python:3.9.6-bullseye
    
    cache:
        paths:
            - .cache/pip/
    
    before_script:
        - set -a; source server/scripts/staging.sh; set +a
        - apt-get update



# 
# Jobs.
#-----------------------------------------------------------------------------------------------------------------------
test:
    stage: test
    
    environment:
        name: staging
        action: prepare
    
    services:
        - memcached:1.6.10-buster
    
    script:
        - apt-get install --yes --no-install-recommends --quiet libmemcached-dev
        - pip install -r requirements/staging.txt
        - mkdir deployment; cp ${DJANGO_SECRETS_FILE} deployment/secrets.py
        - coverage run vazProjects/manage.py test vazProjects
        - coverage report; coverage xml
    
    artifacts:
        reports:
            cobertura: deployment/coverage.xml


launchInstance:
    stage: deploy
    
    environment:
        name: staging
        action: start
        on_stop: terminateInstance
    
    script:
        - apt-get install --yes --no-install-recommends --quiet libmemcached-dev npm awscli
        - npm install --global less
        - pip install -r requirements/staging.txt
        - mkdir deployment; cp ${DJANGO_SECRETS_FILE} deployment/secrets.py
        - server/scripts/deploy.sh staging terminateInstance
        - server/scripts/deploy.sh staging uploadFiles
        - server/scripts/deploy.sh staging launchInstance


terminateInstance:
    stage: deploy
    
    environment:
        name: staging
        action: stop
    
    rules:
        - when: manual
          allow_failure: true
    
    script:
        - apt-get install --yes --no-install-recommends --quiet awscli
        - server/scripts/deploy.sh staging terminateInstance