# 
# VAZ Projects
# 
# 
# Author: Marcelo Tellier Sartori Vaz <marcelotsvaz@gmail.com>



include: .gitlab/ci/*.gitlab-ci.yaml


stages:
  - build
  - test
  - deploy-staging
  - cleanup-staging
  - deploy-production
  - cleanup-production


variables:
    DOCKER_TLS_CERTDIR: /certs/client   # Enable TLS to Docker host. Silence warning in GitLab CI/CD.
    repositorySnapshot: ${CI_PROJECT_URL}/-/archive/${CI_COMMIT_SHA}/vaz-projects.tar.gz
    applicationImage: ${CI_REGISTRY_IMAGE}/application:${CI_COMMIT_SHORT_SHA}
    composeImage: ${CI_REGISTRY_IMAGE}/compose:2.2



# 
# Local jobs.
#-----------------------------------------------------------------------------------------------------------------------
dockerImage:
    stage: build
    extends: .dockerImage


unitTests:
    stage: test
    extends: .unitTests



# 
# Staging jobs.
#-----------------------------------------------------------------------------------------------------------------------
deploy-staging:
    stage: deploy-staging
    extends: .deploy
    environment:
        name: staging
        on_stop: cleanup-staging


staticFiles-staging:
    stage: deploy-staging
    extends: .staticFiles
    environment:
        name: staging
    needs: [ deploy-staging ]


cleanup-staging:
    stage: cleanup-staging
    extends: .cleanup
    environment:
        name: staging



# 
# Production jobs
#-----------------------------------------------------------------------------------------------------------------------
deploy-production:
    stage: deploy-production
    extends: .deploy
    environment:
        name: production
        on_stop: cleanup-production
    rules:
      - when: manual


staticFiles-production:
    stage: deploy-production
    extends: .staticFiles
    environment:
        name: production
    needs: [ deploy-production ]


cleanup-production:
    stage: cleanup-production
    extends: .cleanup
    environment:
        name: production