# 
# VAZ Projects
# 
# 
# Author: Marcelo Tellier Sartori Vaz <marcelotsvaz@gmail.com>



services:
    application:
        extends:
            service: application
            file: &applicationFile application/compose.yaml
        
        image: ${applicationImage-registry.gitlab.com/marcelotsvaz/vaz-projects/application:development}
        build: application/
        
        depends_on:
            postgres:
                condition: service_started
        
        environment:
            DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_MODULE-settings.local}
            djangoSecretKey: django
            domain: vaz-pc.lan
            staticFilesDomain: static-files.vaz-pc.lan
            bucket: ${bucket-local}
            POSTGRES_PASSWORD: &postgresPassword postgres
            ELASTIC_PASSWORD: &elasticsearchPassword elastic
            AWS_ACCESS_KEY_ID:
            AWS_SECRET_ACCESS_KEY:
        
        volumes: [ media:/usr/src/app/deployment/media ]
        
        command:
          - sh
          - -c
          - |-
            ./manage.py migrate --no-input
            ./manage.py search_index --populate
            ./manage.py runserver 0.0.0.0:80
        
        ports: [ 80:80 ]
    
    
    postgres:
        extends:
            service: postgres
            file: database/compose.yaml
        
        environment:
            POSTGRES_PASSWORD: *postgresPassword
        
        network_mode: bridge
        networks: [ default ]
    
    
    memcached:
        extends:
            service: memcached
            file: *applicationFile
    
    
    elasticsearch:
        extends:
            service: elasticsearch
            file: *applicationFile
        
        environment:
            ELASTIC_PASSWORD: *elasticsearchPassword



volumes:
    media:
    postgres: