#
# VAZ Projects
#
#
# Author: Marcelo Tellier Sartori Vaz <marcelotsvaz@gmail.com>



services:
    application:
        image: registry.gitlab.com/marcelotsvaz/vaz-projects/application:development
        build: application/
        
        volumes: [ ./deployment/media:/usr/src/app/deployment/media ]
        
        command:
          - sh
          - -c
          - ./manage.py migrate --no-input;
            ./manage.py search_index --populate;
            ./manage.py runserver 0.0.0.0:8000;
        
        ports: [ 8000:8000 ]
    
    
    postgres:
        volumes: [ ./deployment/database:/var/lib/postgresql/data ]