#
# VAZ Projects
#
#
# Author: Marcelo Tellier Sartori Vaz <marcelotsvaz@gmail.com>



services:
    application:
        image: ${applicationImage-}
        
        depends_on:
            memcached:
                condition: service_started
            elasticsearch:
                condition: service_healthy
        
        environment:
            - DJANGO_SETTINGS_MODULE
            - domainName
            - bucket
        
        volumes:
            - type: bind
              source: ./deployment/
              target: /usr/src/app/deployment/
        
        command: [ uwsgi, --ini, uwsgi.ini ]
        
        ports:
            - 3031:3031
    
    
    memcached:
        image: memcached:1.6.13-bullseye
    
    
    elasticsearch:
        image: elasticsearch:7.16.3
        
        environment:
            discovery.type: single-node
            ES_JAVA_OPTS: -Xms128m -Xmx128m
        
        healthcheck:
            test: curl --silent elasticsearch:9200/_cluster/health/
            interval: 1s
            start_period: 60s