#
# VAZ Projects
#
#
# Author: Marcelo Tellier Sartori Vaz <marcelotsvaz@gmail.com>



services:
    application:
        image: registry.gitlab.com/marcelotsvaz/vaz-projects/application:development
        build: application/
        
        command: [ ./manage.py, runserver, 0.0.0.0:8000 ]
        
        ports:
            - 8000:8000