#
# VAZ Projects
#
#
# Author: Marcelo Tellier Sartori Vaz <marcelotsvaz@gmail.com>



services:
    application:
        extends:
            service: application
            file: application/docker-compose.yaml
        
        image: registry.gitlab.com/marcelotsvaz/vaz-projects/application:development
        build: application/
        
        depends_on:
            postgres:
                condition: service_started
        
        volumes: [ media:/usr/src/app/deployment/media ]
        
        command:
          - sh
          - -c
          - ./manage.py migrate --no-input;
            ./manage.py search_index --populate;
            ./manage.py runserver 0.0.0.0:80;
        
        ports: [ 80:80 ]
    
    
    postgres:
        extends:
            service: postgres
            file: database/docker-compose.yaml
    
    
    memcached:
        extends:
            service: memcached
            file: application/docker-compose.yaml
    
    
    elasticsearch:
        extends:
            service: elasticsearch
            file: application/docker-compose.yaml



volumes:
    media:
    postgres: