#
# VAZ Projects
#
#
# Author: Marcelo Tellier Sartori Vaz <marcelotsvaz@gmail.com>



version: '3.8'



services:
    application:
        image: ${applicationImage-}
        
        environment:
            - DJANGO_SETTINGS_MODULE
            - domainName
            - bucket
        
        volumes:
            - type: bind
              source: ./deployment/
              target: /usr/src/app/deployment/
        
        command: [ uwsgi, --ini, uwsgi.ini ]
        
        ports:
            - 3031:3031
    
    
    memcached:
        image: memcached:1.6.13-bullseye
    
    
    elasticsearch:
        image: elasticsearch:7.16.3
        
        environment:
            discovery.type: single-node
            ES_JAVA_OPTS: -Xms128m -Xmx128m



# depends_on
# restart