#
# VAZ Projects
#
#
# Author: Marcelo Tellier Sartori Vaz <marcelotsvaz@gmail.com>



services:
    application:
        image: ${applicationImage-}
        
        depends_on:
            postgres:
                condition: service_started
            memcached:
                condition: service_started
            elasticsearch:
                condition: service_healthy
        
        environment:
            - DJANGO_SETTINGS_MODULE
            - djangoSecretKey
            - POSTGRES_PASSWORD
            - AWS_ACCESS_KEY_ID
            - AWS_SECRET_ACCESS_KEY
            - domainName
            - bucket
        
        volumes:
            - type: bind
              source: ./deployment/media
              target: /usr/src/app/deployment/media
            - type: bind
              source: ./deployment/tests
              target: /usr/src/app/deployment/tests
        
        command: [ uwsgi, --ini, uwsgi.ini ]
        
        ports:
            - 3031:3031
    
    
    postgres:
        image: postgres:14.1-alpine3.15
        
        environment:
            - POSTGRES_PASSWORD
        
        volumes:
            - type: bind
              source: ./deployment/database/
              target: /var/lib/postgresql/data
    
    
    memcached:
        image: memcached:1.6.13-bullseye
    
    
    elasticsearch:
        image: elasticsearch:7.16.3
        
        environment:
            discovery.type: single-node
            ES_JAVA_OPTS: -Xms128m -Xmx128m
        
        healthcheck:
            test: curl --silent elasticsearch:9200/_cluster/health/
            interval: 1s
            start_period: 60s