# 
# VAZ Projects
# 
# 
# Author: Marcelo Tellier Sartori Vaz <marcelotsvaz@gmail.com>



  - name: Arch Linux custom configuration
    become: true
    connection: community.general.chroot
    
    block:
      - name: Copy files
        copy:
            src: custom.cnf
            dest: /etc/ssl/
            mode: preserve
        
        
      - name: Append to files
        blockinfile:
            path: '{{ item.dir }}/{{ item.file }}'
            block: '{{ lookup( "file", item.file ) }}'
        loop:
          - { file: pacman.conf, dir: /etc/ }
          - { file: bash.bashrc, dir: /etc/ }
          - { file: sshd_config, dir: /etc/ssh/ }
        
        
      - name: Add ".include custom.cnf" to OpenSSL config
        lineinfile:
            path: /etc/ssl/openssl.cnf
            insertbefore: '^\[ new_oids \]$'
            line: .include custom.cnf
        
        
      - name: Remove bash stuff
        shell: rm /etc/skel/.bash*
        
        
      - name: Make SSH dir
        file:
            state: directory
            dest: /etc/skel/.ssh
            mode: 0700
        
        
      - name: Create authorized_keys
        file:
            state: touch
            path: /etc/skel/.ssh/authorized_keys
        
        
      - name: Add admin user
        user:
            name: marcelotsvaz
            groups: wheel