# Generated by Django 3.1.3 on 2021-08-11 16:54

import commonApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userimage',
            options={'verbose_name': 'user image'},
        ),
        migrations.AlterField(
            model_name='userimage',
            name='alt',
            field=models.CharField(blank=True, max_length=250, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='userimage',
            name='attribution',
            field=models.CharField(blank=True, max_length=250, verbose_name='attribution'),
        ),
        migrations.AlterField(
            model_name='userimage',
            name='identifier',
            field=models.SlugField(max_length=100, verbose_name='identifier'),
        ),
        migrations.AlterField(
            model_name='userimage',
            name='image_original',
            field=models.ImageField(upload_to=commonApp.models.getUploadFolder('{}-original', method='identifier'), verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='userimage',
            name='notes',
            field=models.CharField(blank=True, max_length=250, verbose_name='notes'),
        ),
    ]
