# Generated by Django 3.2.6 on 2021-10-04 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commonApp', '0002_auto_20210811_1354'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userimage',
            options={'verbose_name': 'user image', 'verbose_name_plural': 'user images'},
        ),
    ]
