# 
# VAZ Projects
# 
# 
# Author: Marcelo Tellier Sartori Vaz <marcelotsvaz@gmail.com>



  - name: VAZ Projects AMI Build
    hosts: 127.0.0.1
    
    vars:
        disk: /dev/nvme1n1
        mountPoint: /mnt/new
        ansible_chroot_exe: arch-chroot
        ansible_host: '{{ mountPoint }}'
        vazProjects_packages:
          - dehydrated
    
    roles:
      - ext4
      - baseArch
      - customArch
      - ec2
      - monitoring
      - cleanup