# 
# VAZ Projects
# 
# 
# Author: Marcelo Tellier Sartori Vaz <marcelotsvaz@gmail.com>



  - name: VAZ Projects AMI Build
    hosts: default
    
    vars: &vars
        disk: /dev/nvme1n1
        mountPoint: /mnt/new
    
    environment: *vars
    
    roles:
      - ext4
      - baseArch
      - ec2
      - monitoring
      - cleanup