# 
# VAZ Projects
# 
# 
# Author: Marcelo Tellier Sartori Vaz <marcelotsvaz@gmail.com>



http:
    routers:
        toApplication:
            entrypoints: [ https ]
            rule: Host( `{{ env "domain" }}` )
            middlewares: [ securityHeaders ]
            service: application
        
        toMonitoring:
            entrypoints: [ https ]
            rule: Host( `{{ env "monitoringDomain" }}` )
            service: monitoring
        
        toApi:
            entrypoints: [ api ]
            rule: Host( `{{ env "domain" }}` ) && ( PathPrefix( `/api/` ) || PathPrefix( `/dashboard/` ) )
            service: api@internal
    
    
    middlewares:
        securityHeaders:
            headers:
                stsSeconds: 63072000
                stsIncludeSubdomains: true
                stsPreload: true
                referrerPolicy: strict-origin-when-cross-origin
                contentTypeNosniff: true
                frameDeny: true
                browserXssFilter: true
                contentSecurityPolicy: >-
                    default-src 'none';
                    img-src {{ env "staticFilesUrl" }} https://c.disquscdn.com/next/embed/assets/img/ https://referrer.disqus.com/juggler/stat.gif;
                    style-src {{ env "staticFilesUrl" }} https://c.disquscdn.com/next/embed/styles/;
                    font-src {{ env "staticFilesUrl" }};
                    script-src {{ env "staticFilesUrl" }} https://vazprojects.disqus.com/embed.js https://staging-vazprojects.disqus.com/embed.js;
                    connect-src 'self';
                    frame-src https://disqus.com/embed/comments/ https://disqus.com/home/preload/
    
    
    services:
        application:
            loadBalancer:
                servers:
                  - url: http://application:8000
        
        monitoring:
            loadBalancer:
                servers:
                  - url: http://monitoring



tls:
    certificates:
      - certFile: /etc/traefik/website.crt
        keyFile: /etc/traefik/websiteKey.pem
    
    options:
        default:
            sniStrict: true
            preferServerCipherSuites: true
            minVersion: VersionTLS12
            cipherSuites:
              - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256
              - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
            curvePreferences: [ X25519 ]