# 
# VAZ Projects
# 
# 
# Author: Marcelo Tellier Sartori Vaz <marcelotsvaz@gmail.com>



providers:
    file:
        filename: /etc/traefik/dynamic.yaml



entryPoints:
    http:
        address: :80
        
        http:
            redirections:
                entryPoint:
                    to: https
    
    
    https:
        address: :443
        
        http:
            tls: {}
        
        http3: {}
    
    
    privateHttp:
        address: :8080



api: {}



metrics:
    prometheus:
        entryPoint: privateHttp
        buckets:
          - 0.1
          - 0.25
          - 0.5
          - 1.0
          - 2.5
          - 5.0



ping:
    entryPoint: privateHttp



accessLog:
    format: json



experimental:
    http3: true