# 
# VAZ Projects
# 
# 
# Author: Marcelo Tellier Sartori Vaz <marcelotsvaz@gmail.com>



entryPoints:
    http:
        address: :80
        
        http:
            redirections:
                entryPoint:
                    to: https
    
    
    https:
        address: :443
        
        http:
            tls: {}
    
    
    privateHttp:
        address: :8080



providers:
    file:
        filename: /etc/traefik/dynamic.yaml



api:
    dashboard: true



metrics:
    prometheus:
        entryPoint: privateHttp



ping:
    entryPoint: privateHttp



accessLog:
    format: json