# 
# VAZ Projects
# 
# 
# Author: Marcelo Tellier Sartori Vaz <marcelotsvaz@gmail.com>



BASEDIR="${PWD}"
HOOK="$(dirname ${CONFIG})/hooks.sh"

CA='https://acme-v02.api.letsencrypt.org/directory'
# CA='https://acme-staging-v02.api.letsencrypt.org/directory'
PREFERRED_CHAIN='ISRG Root X2'
# PREFERRED_CHAIN='(STAGING) Bogus Broccoli X2'
ACCOUNT_KEY_ALGO='secp384r1'
CONTACT_EMAIL='marcelotsvaz@gmail.com'
CHALLENGETYPE='dns-01'

HOOK_CHAIN='yes'