# 
# VAZ Projects
# 
# 
# Author: Marcelo Tellier Sartori Vaz <marcelotsvaz@gmail.com>



  - name: EC2 instance configuration
    become: true
    block:
      - name: Copy units
        copy:
            src: '{{ item }}'
            dest: '{{ mountPoint }}/usr/local/lib/systemd/system/'
            mode: preserve
        with_fileglob: '*.service'
        
        
      - name: Copy scripts
        copy:
            src: instanceScriptsSetup.sh
            dest: '{{ mountPoint }}/usr/local/lib/'
            mode: preserve
        
        
      - name: Disable systemd-firstboot
        command: arch-chroot {{ mountPoint }} systemctl disable systemd-firstboot
        
        
      - name: Enable services
        command: arch-chroot {{ mountPoint }} systemctl enable {{ item | basename }}
        with_fileglob: '*.service'