# 
# VAZ Projects
# 
# 
# Author: Marcelo Tellier Sartori Vaz <marcelotsvaz@gmail.com>



  - name: EC2 instance configuration
    become: true
    connection: community.general.chroot
    
    block:
      - name: Copy units
        copy:
            src: '{{ item }}'
            dest: /usr/local/lib/systemd/system/
            mode: preserve
        with_fileglob: '*.service'
        
        
      - name: Copy scripts
        copy:
            src: instanceScriptsSetup.sh
            dest: /usr/local/lib/
            mode: preserve
        
        
        # See https://systemd.io/BUILDING_IMAGES/.
      - name: Enable systemd ConditionFirstBoot
        file:
            state: absent
            path: '{{ item }}'
        loop:
          - /etc/machine-id
          - /var/lib/systemd/random-seed
          - /var/lib/systemd/credential.secret
        
        
      - name: Enable services
        systemd:
            enabled: true
            name: '{{ item | basename }}'
        with_fileglob: '*.service'