# 
# VAZ Projects
# 
# 
# Author: Marcelo Tellier Sartori Vaz <marcelotsvaz@gmail.com>



  - name: EC2 instance configuration
    become: true
    connection: community.general.chroot
    
    block:
      - name: Copy units
        copy:
            src: '{{ item }}'
            dest: /usr/local/lib/systemd/system/
            mode: preserve
        with_fileglob: '*.service'
        
        
      - name: Copy scripts
        copy:
            src: instanceScriptsSetup.sh
            dest: /usr/local/lib/
            mode: preserve
        
        
      - name: Disable systemd-firstboot
        systemd:
            enabled: false
            name: systemd-firstboot
        
        
      - name: Enable systemd ConditionFirstBoot
        file:
            state: absent
            path: /etc/machine-id
        
        
      - name: Enable services
        systemd:
            enabled: true
            name: '{{ item | basename }}'
        with_fileglob: '*.service'