# 
# VAZ Projects
# 
# 
# Author: Marcelo Tellier Sartori Vaz <marcelotsvaz@gmail.com>



  - name: EC2 instance configuration
    become: true
    connection: community.general.chroot
    
    block:
      - name: Copy units
        copy:
            src: '{{ item }}'
            dest: /usr/local/lib/systemd/system/
            mode: preserve
        with_fileglob: '*.service'
        
        
      - name: Copy scripts
        copy:
            src: instanceScriptsSetup.sh
            dest: /usr/local/lib/
            mode: preserve
        
        
      - name: Disable systemd-firstboot
        command: systemctl disable systemd-firstboot
        
        
      - name: Enable services
        command: systemctl enable {{ item | basename }}
        with_fileglob: '*.service'