# 
# VAZ Projects
# 
# 
# Author: Marcelo Tellier Sartori Vaz <marcelotsvaz@gmail.com>



services:
    grafana:
        image: grafana/grafana:9.0.2
        
        restart: unless-stopped
        
        environment:
            monitoringDomain:
            GF_SECURITY_ADMIN_PASSWORD:
        
        volumes:
          - ./config/grafana:/etc/grafana
          - grafana:/var/lib/grafana
        
        ports: [ 80:3000 ]
    
    
    prometheus:
        image: prom/prometheus:v2.36.2
        
        restart: unless-stopped
        
        volumes:
          - ../deployment/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
          - prometheus:/prometheus
            
        ports: [ 9090:9090 ]
        
        command:
          - --config.file=/etc/prometheus/prometheus.yaml
          - --storage.tsdb.path=/prometheus
          - --storage.tsdb.retention.size=2GB
    
    
    loki:
        image: grafana/loki:2.6.0
        
        restart: unless-stopped
        
        volumes:
          - ./config/loki.yaml:/etc/loki/local-config.yaml:ro
          - loki:/loki
            
        ports: [ 3100:3100 ]



volumes:
    grafana:
    prometheus:
    loki: