# 
# VAZ Projects
# 
# 
# Author: Marcelo Tellier Sartori Vaz <marcelotsvaz@gmail.com>



services:
    grafana:
        image: grafana/grafana:10.2.0
        
        restart: unless-stopped
        
        environment:
            monitoringDomain:
            # Secrets.
            GF_SECURITY_ADMIN_PASSWORD:
        
        configs:
          - source: grafana
            target: /etc/grafana
        
        volumes: [ grafana:/var/lib/grafana ]
        
        ports: [ 80:3000 ]  # Application.
    
    
    prometheus:
        image: prom/prometheus:v2.47.2
        
        restart: unless-stopped
        
        configs:
          - source: prometheus
            target: /etc/prometheus/prometheus.yaml
        
        volumes: [ prometheus:/prometheus ]
            
        ports: [ 9090:9090 ]    # API and dashboard.
        
        command:
          - --config.file=/etc/prometheus/prometheus.yaml
          - --storage.tsdb.path=/prometheus
          - --storage.tsdb.retention.size=2GB
    
    
    loki:
        image: grafana/loki:2.9.2
        
        restart: unless-stopped
        
        configs:
          - source: loki
            target: /etc/loki/local-config.yaml
        
        volumes: [ loki:/loki ]
            
        ports: [ 3100:3100 ]    # API and dashboard.



configs:
    grafana:
        file: ./config/grafana
    prometheus:
        file: ../deployment/prometheus.yaml
    loki:
        file: ./config/loki.yaml



volumes:
    grafana:
    prometheus:
    loki: