# 
# VAZ Projects
# 
# 
# Author: Marcelo Tellier Sartori Vaz <marcelotsvaz@gmail.com>



services:
    grafana:
        image: grafana/grafana:8.2.6
        
        environment:
            GF_SERVER_ROOT_URL: https://${domainName}
            GF_SECURITY_ADMIN_PASSWORD:
        
        volumes: [ grafana:/var/lib/grafana ]
        
        ports: [ 80:3000 ]
    
    
    prometheus:
        image: prom/prometheus:v2.33.3
        
        volumes:
          - ./config/prometheus.yaml:/etc/prometheus/prometheus.yml:ro
          - prometheus:/prometheus
            
        ports: [ 9090:9090 ]
    
    
    loki:
        image: grafana/loki:2.4.2
        
        volumes:
          - ./config/loki.yaml:/etc/loki/local-config.yaml:ro
          - loki:/loki
            
        ports: [ 3100:3100 ]
    
    
    node-exporter:
        image: prom/node-exporter:v1.3.1
        
        volumes: [ '/:/mnt/host:ro,rslave' ]
        
        pid: host
        network_mode: host
        
        command: [ --path.rootfs=/mnt/host ]
    
    
    promtail:
        image: grafana/promtail:2.4.2
        
        environment:
          - hostname
        
        volumes:
          - ./config/promtail.yaml:/etc/promtail/config.yml:ro
          - /var/log/journal:/mnt/logs/journal
        
        command: [ -config.file=/etc/promtail/config.yml, -config.expand-env=true ]



volumes:
    grafana:
    prometheus:
    loki: