#
# VAZ Projects
#
#
# Author: Marcelo Tellier Sartori Vaz <marcelotsvaz@gmail.com>



services:
    grafana:
        image: grafana/grafana:8.2.6
        
        environment:
          - GF_SECURITY_ADMIN_PASSWORD
        
        volumes: [ grafana:/var/lib/grafana ]
        
        ports: [ 80:3000 ]
    
    
    loki:
        image: grafana/loki:2.4.2
        
        volumes: [ ./config/loki.yaml:/etc/loki/local-config.yaml:ro ]
            
        ports: [ 3100:3100 ]
    
    
    promtail:
        image: grafana/promtail:2.4.2
        
        volumes: [ ./config/promtail.yaml:/etc/promtail/config.yml:ro ]



volumes:
    grafana: