# Generated by Django 3.1.3 on 2021-08-06 04:47

import commonApp.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('short_description', commonApp.fields.TextField(verbose_name='short description')),
                ('published', models.BooleanField(default=False, verbose_name='published')),
                ('description', commonApp.fields.TextField(blank=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'project',
            },
        ),
    ]
