# Generated by Django 3.2.6 on 2021-08-26 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectsApp', '0002_remove_project_single_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='last_edited',
            field=models.DateTimeField(auto_now=True, verbose_name='last edited'),
        ),
        migrations.AlterField(
            model_name='project',
            name='base_last_edited',
            field=models.DateTimeField(auto_now=True, verbose_name='base last edited'),
        ),
    ]
