# 
# VAZ Projects
# 
# 
# Author: Marcelo Tellier Sartori Vaz <marcelotsvaz@gmail.com>



  - name: Enable systemd ConditionFirstBoot
    become: true
    ansible.builtin.command: rm {{ mountPoint }}/etc/machine-id


  - name: Unmount the root partition
    become: true
    ansible.posix.mount:
        path: '{{ mountPoint }}'
        state: unmounted
        fstab: /tmp/tmp.fstab