# 
# VAZ Projects
# 
# 
# Author: Marcelo Tellier Sartori Vaz <marcelotsvaz@gmail.com>



  - name: Arch Linux install cleanup
    become: true
    block:
      - name: Enable systemd ConditionFirstBoot
        command: rm {{ mountPoint }}/etc/machine-id
        
        
      - name: Unmount the root partition
        ansible.posix.mount:
            path: '{{ mountPoint }}'
            state: unmounted
            fstab: /tmp/tmp.fstab