# 
# VAZ Projects
# 
# 
# Author: Marcelo Tellier Sartori Vaz <marcelotsvaz@gmail.com>



  - name: Arch Linux install cleanup
    become: true
    
    block:
      - name: Unmount the root partition
        ansible.posix.mount:
            state: unmounted
            path: '{{ mountPoint }}'
            fstab: /tmp/tmp.fstab