# 
# VAZ Projects
# 
# 
# Author: Marcelo Tellier Sartori Vaz <marcelotsvaz@gmail.com>



services:
    postgres:
        image: postgres:14.4-alpine3.16
        
        restart: unless-stopped
        
        environment:
            # Secrets.
          - POSTGRES_PASSWORD
        
        volumes: [ postgres:/var/lib/postgresql/data ]
        
        ports: [ 5432:5432 ]
        
        healthcheck:
            test: pg_isready --username postgres
            interval: 5s
            start_period: 10s



volumes:
    postgres: