# 
# VAZ Projects
# 
# 
# Author: Marcelo Tellier Sartori Vaz <marcelotsvaz@gmail.com>



services:
    postgres:
        image: postgres:14.4-alpine3.16
        
        restart: unless-stopped
        
        environment:
            # Secrets.
          - POSTGRES_PASSWORD
        
        configs:
          - source: stagingDatabaseFixture
            target: /docker-entrypoint-initdb.d/stagingFixture.sql
        
        volumes: [ postgres:/var/lib/postgresql/data ]
        
        ports: [ 5432:5432 ]    # API.
        
        healthcheck:
            test: pg_isready --username postgres
            interval: 5s
            start_period: 10s



configs:
    stagingDatabaseFixture:
        file: ./scripts/stagingFixture.sql



volumes:
    postgres: