# 
# VAZ Projects
# 
# 
# Author: Marcelo Tellier Sartori Vaz <marcelotsvaz@gmail.com>



  - name: Arch Linux base install
    become: true
    
    block:
      - name: Get packages from all roles
        set_fact:
            packages: '{{ packages | default( [] ) + lookup( "vars", item ) }}'
        with_varnames: ^.*_packages$
        
        
      - name: Run pacstrap
        command: pacstrap -c {{ mountPoint }} --noprogressbar {{ packages | join( ' ' ) }}
        
        
      - name: Setup DNS
        command: ln -sf /run/systemd/resolve/resolv.conf {{ mountPoint }}/etc/resolv.conf
        
        
      - name: Generate fstab
        shell: genfstab -U {{ mountPoint }} >> {{ mountPoint }}/etc/fstab
    
    
    
  - name: Arch Linux base configuration
    become: true
    connection: community.general.chroot
    
    block:
      - name: Set time zone
        command: ln -sf /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime
        
        
      - name: Enable locales
        lineinfile:
            path: /etc/locale.gen
            regex: ^#?({{ item }})
            line: '\1'
            backrefs: true
        loop:
          - 'en_US\.UTF-8 UTF-8'
          - 'pt_BR\.UTF-8 UTF-8'
        
        
      - name: Generate locales
        command: locale-gen
        
        
      - name: Set locale
        copy:
            content: LANG=en_US.UTF-8
            dest: /etc/locale.conf
        
        
      - name: Copy network unit
        copy:
            src: main.network
            dest: /etc/systemd/network/
            mode: preserve
        
        
      - name: Enable services
        shell: systemctl enable systemd-{networkd,resolved,timesyncd} sshd
        
        
      - name: Add wheel group to sudoers
        copy:
            content: '%wheel ALL=(ALL) NOPASSWD: ALL'
            dest: /etc/sudoers.d/wheel
        
        
        
        # Install bootloader.
        #---------------------------------------------------------------------------
      - name: Install GRUB
        command: grub-install {{ disk }}
        
        
      - name: Change GRUB config
        lineinfile:
            path: /etc/default/grub
            regex: ^{{ item.var }}=
            line: '{{ item.var }}={{ item.value }}'
        loop:
          - { var: 'GRUB_CMDLINE_LINUX_DEFAULT', value: "'nomodeset console=ttyS0,9600n8 earlyprintk=serial,ttyS0,9600 loglevel=6'" }
          - { var: 'GRUB_TIMEOUT', value: 0 }
        
        
      - name: Generate GRUB config file
        command: grub-mkconfig -o /boot/grub/grub.cfg