# 
# VAZ Projects
# 
# 
# Author: Marcelo Tellier Sartori Vaz <marcelotsvaz@gmail.com>



  - name: Run pacstrap
    become: true
    ansible.builtin.command: pacstrap -c {{ mountPoint }} --noprogressbar {{ packages | join( ' ' ) }}
    vars:
        packages:
          - base
          - linux
          - grub
          - openssh
          - sudo
          - aws-cli
          - gdisk
          - nano
          - docker
          - docker-compose
          - prometheus-node-exporter
          - promtail
          - dehydrated


  - name: Setup DNS
    become: true
    ansible.builtin.command: ln -sf /run/systemd/resolve/resolv.conf {{ mountPoint }}/etc/resolv.conf


  - name: Generate fstab
    become: true
    ansible.builtin.shell: genfstab -U {{ mountPoint }} >> {{ mountPoint }}/etc/fstab


  - name: Copy chroot.sh
    become: true
    ansible.builtin.copy:
        src: chroot.sh
        dest: '{{ mountPoint }}'
        mode: preserve


  - name: Run chroot.sh
    become: true
    ansible.builtin.command: arch-chroot {{ mountPoint }} /chroot.sh


  - name: Delete chroot.sh
    become: true
    ansible.builtin.command: rm {{ mountPoint }}/chroot.sh