# 
# VAZ Projects
# 
# 
# Author: Marcelo Tellier Sartori Vaz <marcelotsvaz@gmail.com>



services:
    nginx:
        image: nginx:1.23-alpine
        
        restart: unless-stopped
        
        environment:
          - domain
          - staticFilesDomain
          - privateDomain
          - monitoringDomain
        
        configs:
          - source: nginx
            target: /etc/nginx/templates/default.conf.template
        
        secrets:
          - source: certificate
            target: /etc/nginx/tls/website.crt
          - source: certificateKey
            target: /etc/nginx/tls/websiteKey.pem
        
        ports:
            - 80:80
            - 443:443



configs:
    nginx:
        file: ./config/nginx.conf



secrets:
    certificate:
        file: ../deployment/tls/website.crt
    certificateKey:
        file: ../deployment/tls/websiteKey.pem