# 
# VAZ Projects
# 
# 
# Author: Marcelo Tellier Sartori Vaz <marcelotsvaz@gmail.com>



services:
    nginx:
        image: nginx:1.23-alpine
        
        restart: unless-stopped
        
        environment:
          - domain
          - staticFilesDomain
          - privateDomain
          - monitoringDomain
        
        volumes:
            - ./config/nginx.conf:/etc/nginx/templates/default.conf.template:ro
            - ../deployment/tls:/etc/nginx/tls:ro
        
        ports:
            - 80:80
            - 443:443