# 
# VAZ Projects
# 
# 
# Author: Marcelo Tellier Sartori Vaz <marcelotsvaz@gmail.com>



services:
    traefik:
        image: traefik:2.10.6
        
        restart: unless-stopped
        
        environment:
          - domain
          - staticFilesUrl
          - monitoringDomain
        
        configs:
          - source: traefikStatic
            target: /etc/traefik/traefik.yaml
          - source: traefikDynamic
            target: /etc/traefik/dynamic.yaml
        
        secrets:
          - source: certificate
            target: /etc/traefik/website.crt
          - source: certificateKey
            target: /etc/traefik/websiteKey.pem
        
        ports:
          - 80:80 # HTTP entrypoint.
          - 443:443/tcp # HTTPS entrypoint.
          - 443:443/udp # HTTPS entrypoint (HTTP/3).
          - 8080:8080 # Dashboard and API.
        
        healthcheck:
            test: traefik healthcheck
            interval: 5s
            start_period: 5s



configs:
    traefikStatic:
        file: ./config/traefik/static.yaml
    traefikDynamic:
        file: ./config/traefik/dynamic.yaml



secrets:
    certificate:
        file: ../deployment/tls/website.crt
    certificateKey:
        file: ../deployment/tls/websiteKey.pem