# 
# VAZ Projects
# 
# 
# Author: Marcelo Tellier Sartori Vaz <marcelotsvaz@gmail.com>



services:
    nginx:
        image: nginx:1.23-alpine
        
        restart: unless-stopped
        
        environment:
          - domain
          - staticFilesDomain
          - privateDomain
          - monitoringDomain
        
        volumes:
            - ./config/nginx.conf:/etc/nginx/templates/default.conf.template:ro
            - ../deployment/tls:/etc/nginx/tls:ro
            - nginxLogs:/mnt/logs/nginx
        
        ports:
            - 80:80
            - 443:443
    
    
    promtail:
        extends:
            service: promtail
            file: ../monitoring/compose.common.yaml
        
        volumes:
          - ./config/promtail.yaml:/etc/promtail/config.yml:ro
          - nginxLogs:/mnt/logs/nginx



volumes:
    nginxLogs: