# 
# VAZ Projects
# 
# 
# Author: Marcelo Tellier Sartori Vaz <marcelotsvaz@gmail.com>



services:
    traefik:
        image: traefik:2.9
        
        restart: unless-stopped
        
        environment:
          - domain
          - staticFilesUrl
        
        # volumes: [ ../deployment/logs/traefikAccess.log:/var/log/traefikAccess.log ]
        
        configs:
          - source: traefikStatic
            target: /etc/traefik/traefik.yaml
          - source: traefikDynamic
            target: /etc/traefik/dynamic.yaml
        
        secrets:
          - source: certificate
            target: /etc/traefik/website.crt
          - source: certificateKey
            target: /etc/traefik/websiteKey.pem
        
        ports:
          - 80:80
          - 443:443
          - 8080:8080



configs:
    traefikStatic:
        file: ./config/traefik/static.yaml
    traefikDynamic:
        file: ./config/traefik/dynamic.yaml



secrets:
    certificate:
        file: ../deployment/tls/website.crt
    certificateKey:
        file: ../deployment/tls/websiteKey.pem