# 
# VAZ Projects
# 
# 
# Author: Marcelo Tellier Sartori Vaz <marcelotsvaz@gmail.com>



  - name: Create partitions and filesystems
    become: true
    
    block:
        # Partitioning.
        #-------------------------------------------------------------------------------
      - name: Create partition table
        command: sgdisk --clear {{ disk }}
        
        
      - name: Create EFI partition
        command: sgdisk --new 1:0:+100M --change-name 1:EFI --typecode 1:ef00 {{ disk }}
        
        
      - name: Create root partition
        command: sgdisk --new 2:0:0 --change-name 2:Root {{ disk }}
        
        
      - name: Get root partition UUID
        shell: lsblk -nro PATH,PARTUUID | grep '^{{ disk }}p2 ' | cut -d ' ' -f2
        register: rootPartitionUuid
        
        
      - name: Register root partition UUID
        set_fact:
            rootPartitionUuid: '{{ rootPartitionUuid.stdout }}'
        
        
        
        # Formatting.
        #-------------------------------------------------------------------------------
      - name: Format EFI partition to FAT32
        community.general.filesystem:
            dev: '{{ disk }}p1'
            fstype: vfat
            opts: -F 32
        
        
      - name: Format root partition to ext4
        community.general.filesystem:
            dev: '{{ disk }}p2'
            fstype: ext4
        
        
        
        # Mounting.
        #-------------------------------------------------------------------------------
      - name: Mount root partition
        ansible.posix.mount:
            state: mounted
            src: '{{ disk }}p2'
            path: '{{ mountPoint }}'
            fstype: ext4
            fstab: /tmp/tmp.fstab
        
        
      - name: Mount EFI partition
        ansible.posix.mount:
            state: mounted
            src: '{{ disk }}p1'
            path: '{{ mountPoint }}/boot/efi'
            fstype: vfat
            fstab: /tmp/tmp.fstab