# 
# VAZ Projects
# 
# 
# Author: Marcelo Tellier Sartori Vaz <marcelotsvaz@gmail.com>



  - name: Create partitions and filesystems
    become: true
    
    block:
      - name: Create partition table
        command: sgdisk --clear {{ disk }}
        
        
      - name: Create boot partition
        command: sgdisk --new 1:0:+1M --change-name 1:'Boot' --typecode 1:ef02 {{ disk }}
        
        
      - name: Create root partition
        command: sgdisk --new 2:0:0 --change-name 2:'Root' {{ disk }}
        
        
      - name: Create Ext4 filesystem
        community.general.filesystem:
            dev: '{{ disk }}p2'
            fstype: ext4
        
        
      - name: Mount the root partition
        ansible.posix.mount:
            state: mounted
            src: '{{ disk }}p2'
            path: '{{ mountPoint }}'
            fstype: ext4
            fstab: /tmp/tmp.fstab