# 
# VAZ Projects
# 
# 
# Author: Marcelo Tellier Sartori Vaz <marcelotsvaz@gmail.com>



global:
    scrape_interval: 15s
    evaluation_interval: 15s



scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: [ localhost:9090 ]
    
    
  - job_name: node
    ec2_sd_configs:
      - port: 9100
        filters:
          - name: tag:Environment
            values: [ ${environment} ]
    relabel_configs:
      - source_labels: [ __meta_ec2_tag_Name ]
        target_label: instance
      - source_labels: [ __meta_ec2_instance_id ]
        target_label: instance_id