# 
# VAZ Projects
# 
# 
# Author: Marcelo Tellier Sartori Vaz <marcelotsvaz@gmail.com>



global:
    scrape_interval: 15s
    evaluation_interval: 15s



scrape_configs:
  - job_name: Prometheus
    static_configs:
      - targets: [ localhost:9090 ]
    
    
  - job_name: Node Exporter
    ec2_sd_configs:
      - port: 9100
        filters: &filterEnvironment
          - name: tag:Environment
            values: [ ${environment} ]
    relabel_configs: &ec2Labels
      - source_labels: [ __meta_ec2_tag_Name ]
        target_label: instance
      - source_labels: [ __meta_ec2_instance_id ]
        target_label: instance_id
    
    
  - job_name: Docker Engine
    ec2_sd_configs:
      - port: 9323
        filters: *filterEnvironment
    relabel_configs: *ec2Labels
    
    
  - job_name: cAdvisor
    ec2_sd_configs:
      - port: 9080
        filters: *filterEnvironment
    relabel_configs: *ec2Labels