# 
# VAZ Projects
# 
# 
# Author: Marcelo Tellier Sartori Vaz <marcelotsvaz@gmail.com>



global:
    scrape_interval: 15s
    evaluation_interval: 15s



scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: [ localhost:9090 ]
    
    
  - job_name: node
    static_configs:
      - targets: [ load-balancer:9100 ]
      - targets: [ application:9100 ]
      - targets: [ postgres:9100 ]
      - targets: [ monitoring:9100 ]