# Generated by Django 3.2.6 on 2021-10-06 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0002_rename_post_blogpost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='description',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='name',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='thumbnail_original',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title',
            field=models.CharField(default='title', max_length=100, verbose_name='title'),
            preserve_default=False,
        ),
    ]
