# Generated by Django 3.2.6 on 2021-10-06 02:27

import commonApp.fields
import commonApp.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='slug')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('banner_original', models.ImageField(upload_to=commonApp.models.getUploadFolder('banner-original'), verbose_name='banner')),
                ('thumbnail_original', models.ImageField(upload_to=commonApp.models.getUploadFolder('thumbnail-original'), verbose_name='thumbnail')),
                ('description', commonApp.fields.TextField(verbose_name='description')),
                ('content', commonApp.fields.MarkdownField(verbose_name='content')),
                ('draft', models.BooleanField(default=True, verbose_name='draft')),
                ('posted', models.DateTimeField(default=django.utils.timezone.now, verbose_name='posted')),
                ('last_edited', models.DateTimeField(auto_now=True, verbose_name='last edited')),
            ],
            options={
                'verbose_name': 'post',
                'verbose_name_plural': 'posts',
                'ordering': ('posted',),
            },
        ),
    ]
