{
 "title": "Application Overview",
 "description": "High level metrics for monitoring application health and performance.",
 "tags": [ "Monitoring" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total{service=\"application@file\"}[$__rate_interval:$__interval]))",
     "legendFormat": "Traefik"
    }
   ]
  },
  {
   "title": "Saturation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - sum(rate(node_cpu_seconds_total{instance=\"VAZ Projects Application Server\",mode=\"idle\"}[$__rate_interval:$__interval])) / sum(machine_cpu_cores{instance=\"VAZ Projects Application Server\"})",
     "legendFormat": "Application Server"
    }
   ]
  },
  {
   "title": "Latency (95th percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.94999999999999996, sum by (le) (rate(traefik_service_request_duration_seconds_bucket{service=\"application@file\"}[$__rate_interval:$__interval])))",
     "legendFormat": "2xx"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(traefik_service_requests_total{service=\"application@file\",code=~\"5..\"}[$__rate_interval:$__interval])) / sum(rate(traefik_service_requests_total{service=\"application@file\"}[$__rate_interval:$__interval])) or vector( 0 )",
     "legendFormat": "Traefik"
    }
   ]
  }
 ]
}