# 
# VAZ Projects
# 
# 
# Author: Marcelo Tellier Sartori Vaz <marcelotsvaz@gmail.com>



.cleanup:
    environment:
        action: stop
    
    rules:
      - when: manual
        allow_failure: true
    
    image:
        name: hashicorp/terraform:1.3.6
        entrypoint: [ '' ]
    
    cache:
        key: ${CI_COMMIT_REF_SLUG}-terraform    # Per-branch Terraform cache.
        paths: [ deployment/terraform/providers/ ]
        policy: pull
    
    script:
      - apk add bash
      - deploy/deploy.sh ${CI_ENVIRONMENT_TIER} destroyEnvironment