# 
# VAZ Projects
# 
# 
# Author: Marcelo Tellier Sartori Vaz <marcelotsvaz@gmail.com>



.deploy:
    environment:
        action: start
    
    image:
        name: hashicorp/terraform:1.3.6
        entrypoint: [ '' ]
    
    cache:
        key: ${CI_COMMIT_REF_SLUG}-terraform    # Per-branch Terraform cache.
        paths: [ deployment/terraform/providers/ ]
    
    script:
      - apk add --no-cache bash tar aws-cli openssl
      - wget https://raw.githubusercontent.com/dehydrated-io/dehydrated/v0.7.1/dehydrated -O /bin/dehydrated && chmod +x ${_}
      - deploy/deploy.sh ${CI_ENVIRONMENT_TIER} deployEnvironment
      - cp
            deployment/terraform/vazProjects-${CI_ENVIRONMENT_TIER}-application/*/environment.env
            deployment/applicationEnvironment.env
    
    retry:
        when: script_failure
        max: 1
    
    artifacts:
        paths: [ deployment/applicationEnvironment.env ]
        reports:
            terraform: deployment/terraformChanges.json
        name: ${CI_ENVIRONMENT_TIER}