# 
# VAZ Projects
# 
# 
# Author: Marcelo Tellier Sartori Vaz <marcelotsvaz@gmail.com>



# 
# Jobs.
#-----------------------------------------------------------------------------------------------------------------------
.dockerImage:
    services: [ docker:20.10-dind ]
    
    image: docker:20.10
    
    interruptible: true
    
    script:
      - echo ${CI_REGISTRY_PASSWORD} | docker login --username ${CI_REGISTRY_USER} --password-stdin ${CI_REGISTRY}
      - docker buildx install
      - cd application
      - docker compose -f compose.build.yaml build
      - docker tag ${CI_REGISTRY_IMAGE}/application:latest ${applicationImage}
      - docker push --all-tags --quiet ${CI_REGISTRY_IMAGE}/application