# 
# VAZ Projects
# 
# 
# Author: Marcelo Tellier Sartori Vaz <marcelotsvaz@gmail.com>



# 
# Jobs.
#-----------------------------------------------------------------------------------------------------------------------
.dockerImage:
    services: [ docker:20.10-dind ]
    
    image: docker:20.10
    
    interruptible: true
    
    cache:
        paths: [ deployment/buildkitCache/ ]
    
    script:
      - echo ${CI_REGISTRY_PASSWORD} | docker login --username ${CI_REGISTRY_USER} --password-stdin ${CI_REGISTRY}
      - docker buildx create --driver docker-container --use
      - docker buildx bake --file application/compose.build.yaml