# 
# VAZ Projects
# 
# 
# Author: Marcelo Tellier Sartori Vaz <marcelotsvaz@gmail.com>



.dockerImage:
    services: [ docker:23.0-dind ]
    
    image: docker:23.0
    
    tags: [ docker ]
    
    interruptible: true
    
    cache:
        key: ${CI_COMMIT_REF_SLUG}-buildkit # Per-branch BuildKit cache.
        paths: [ deployment/buildkitCache/ ]
    
    script:
      - echo ${CI_REGISTRY_PASSWORD} | docker login
            --username ${CI_REGISTRY_USER} --password-stdin ${CI_REGISTRY}
      - docker context create gitlab  # docker buildx create needs explicit context instead of env vars.
      - docker buildx create gitlab --driver docker-container --driver-opt image=moby/buildkit:v0.10.4 --use
      - cd application/
      - docker buildx bake --file build.compose.yaml