# 
# VAZ Projects
# 
# 
# Author: Marcelo Tellier Sartori Vaz <marcelotsvaz@gmail.com>



# 
# Jobs.
#-----------------------------------------------------------------------------------------------------------------------
.dockerImage:
    services: [ docker:20.10-dind ]
    
    image: ${composeImage}
    
    interruptible: true
    
    script:
      - echo ${CI_REGISTRY_PASSWORD} | docker login --username ${CI_REGISTRY_USER} --password-stdin ${CI_REGISTRY}
      - docker build --pull --tag ${applicationImage} application
      - docker push --quiet ${applicationImage}