# 
# VAZ Projects
# 
# 
# Author: Marcelo Tellier Sartori Vaz <marcelotsvaz@gmail.com>



.unitTests:
    services: [ docker:23.0-dind ]
    
    image: docker:23.0
    
    interruptible: true
    
    script:
      - mkdir -p deployment/tls/ && cd deployment/tls/
      - openssl genpkey -algorithm EC -pkeyopt ec_paramgen_curve:prime256v1 -out websiteKey.pem
      - openssl req
          -x509 -subj /
          -addext 'subjectAltName = DNS:localhost, DNS:minio'
          -key websiteKey.pem
          -sha512
          -out website.crt
      - cd ../../
      - echo ${CI_REGISTRY_PASSWORD} | docker login
            --username ${CI_REGISTRY_USER} --password-stdin ${CI_REGISTRY}
      - docker compose up --no-build --detach --quiet-pull
      - docker compose exec --no-TTY application coverage run manage.py test
      - docker compose exec --no-TTY application coverage report
      - docker compose exec --no-TTY application coverage xml
      - docker compose cp application:/home/django/deployment/tests/unitTests.xml .
      - docker compose cp application:/home/django/deployment/tests/coverage.xml .
    
    coverage: /^TOTAL.+?(\d+(?:\.\d+)?\%)$/
    
    artifacts:
        reports:
            junit: unitTests.xml
            coverage_report:
                coverage_format: cobertura
                path: coverage.xml